version: '3.8'

services:
  api:
    image: my-api:latest
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  db-data:
